### ISSUE TITLE
Export to window

### ISSUE THREAD

**Issue by tiagoporto** [yatki/read-env#31]
Hi @yatki , helpful package man!!
I'm trying to use the browser version but it's not working.
I'm using the version 2.
Could you add an example in the docs?
Thank you

**Comment by yatki** [comment]
Hey @tiagoporto 

Here is a working example.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="https://unpkg.com/read-env@2.0.0/dist/index.umd.js"></script>
  <script type="text/javascript">
  const variables = window.readEnv('EXAMPLE');
  </script>
</body>
</html>
```

But please make sure your `process.env` variable is defined in your browser environment. If you are providing your environment variables with a different variable you can use `source` option. See: https://github.com/yatki/read-env#optionssource

Hope this helps,
Cheers 🖖🏻 ,
